# basic
title: 追客
subtitle: 热爱生活，热爱编程，Web前端见习魔法师
favicon: favicon.ico
avatar: images/avatar.png

# disqus
disqus_shortname: drakeleung

# social
social:
  github: https://github.com/DrakeLeung
  twitter: https://twitter.com/DrakeLeung
  weibo: http://weibo.com/cha12chalyc

# nav #
nav:
  home: .
  archive: archives
  about: about

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
